services:
  backend:
    build:
      context: ../Backend
      dockerfile: Dockerfile
    container_name: streamline-backend
    restart: unless-stopped
    expose:
      - "8000"
    env_file:
      - .env
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - uploads_data:/app/uploads
    networks:
      - streamline-network
    deploy:
      resources:
        limits:
          memory: 1G

  frontend:
    build:
      context: ../Frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://${DOMAIN}/api
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
        NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
        NEXT_PUBLIC_USE_MOCK: "false"
    container_name: streamline-frontend
    restart: unless-stopped
    expose:
      - "3000"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - streamline-network
    deploy:
      resources:
        limits:
          memory: 1G

  nginx:
    image: nginx:alpine
    container_name: streamline-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - uploads_data:/uploads:ro
      - certbot_www:/var/www/certbot:ro
      - certbot_conf:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend
    networks:
      - streamline-network
  certbot:
    image: certbot/certbot
    container_name: streamline-certbot
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt
    networks:
      - streamline-network

  netdata:
    image: netdata/netdata
    container_name: streamline-netdata
    restart: unless-stopped
    ports:
      - "19999:19999"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdata_config:/etc/netdata
      - netdata_lib:/var/lib/netdata
      - netdata_cache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - streamline-network

volumes:
   uploads_data:
   netdata_config:
   netdata_lib:
   certbot_www:
   certbot_conf:
   netdata_cache:

networks:
  streamline-network:
    driver: bridge
